function DK = DK(Q)
%DK
%    DK = DK(Q)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    22-Nov-2025 18:10:24

t2 = cos(Q);
t3 = sin(Q);
DK = reshape([0.0,1.0./3.0,0.0,0.0,1.0./6.0e+1,1.0./3.0,0.0,1.0./3.0,0.0,0.0,-1.0./6.0e+1,1.0./3.0,t3.*(-1.0./3.0),t2./3.0,0.0,t2./6.0e+1+1.0./6.0e+1,t3./6.0e+1,1.0./3.0,-1.0./6.0e+1,0.0,-1.0./3.0],[3,7]);
end
